(+ 1 (let ([a 2])
  (+ a (let ([b 2])
    (+ b (let ([c 2])
      (+ c (let ([d 2])
        (+ d (let ([e 2])
          (+ e (let ([f 2])
            (+ f (let ([g 2])
              (+ g (let ([h 2])
                (+ h (let ([i 2])
                  (+ i (let ([j 2])
                    (+ j (let ([k 2])
                      (+ k (let ([l 2])
                        (+ l (let ([m 2])
                          (+ m (let ([n 2])
                            (+ n (let ([o 2])
                              (+ o (let ([p 2]) p))))))))))))))))))))))))))))))))